# https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI
on:
  push:
    branches: main
    paths:
    - "*/*.ys"
    - .github/workflows/*.ya?ml

  workflow_dispatch:
    inputs:
      schema:
        description: Specify a particular schema to compile.
        type: string

  schedule:
  - cron: 0 5 * * * # 5AM daily

jobs:
  CI:
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    env:
      draft: 2020-12
      CDN: cdn.statically.io
      BRANCH: json

    steps:
    - name: Checkout & install YAMLScript
      uses: yaml/yamlscript-workflow-action@main
      with:
        ys-file: /dev/null

    - name: Set Environment
      run: env >> $GITHUB_ENV
      env:
        schema: https://json-schema.org/draft/${{ env.draft }}/schema
        ref: /gh/${{ github.repository }}/refs/heads/${{ env.BRANCH }}

    - name: Compile Schemas
      id: compile
      shell: /bin/zsh --no-rcs --err-exit --pipe-fail {0}
      run: >-
        mkdir $BRANCH &&
        for file (*/${{ inputs.schema || '*' }}.ys) ys --json $file |
          jq --indent ${TABSIZE:-2} > $BRANCH/$file:t:r.json
      env:
        URL: https://${{ env.CDN }}${{ env.ref }}

    - name: Deploy
      if: inputs.schema == '' && steps.compile.conclusion == 'success'
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        FOLDER: ${{ env.BRANCH }}
        MESSAGE: "{msg}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
