# https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI
on:
  push:
    branches: main
    paths:
    - "*/*.ys"
    - .github/workflows/*.ya?ml

  workflow_dispatch:
    inputs:
      schema:
        description: Specify a particular schema to compile.
        type: string

  schedule:
  - cron: 0 5 * * * # 5AM daily

jobs:
  CI:
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    env:
      ACTIONS_STEP_DEBUG: ${{ vars.ACTIONS_STEP_DEBUG }}
      draft: 2020-12
      CDN: cdn.statically.io
      BRANCH: json

    steps:
    - name: Checkout & install YS
      uses: yaml/yamlscript-workflow-action@9658b54c28ba47b5bcc74dfe29d636908fcb158f
      with:
        ys-file: /dev/null

    - name: Set Environment
      run: env >> $GITHUB_ENV
      env:
        schema: https://json-schema.org/draft/${{ env.draft }}/schema
        ref: /gh/${{ github.repository }}/refs/heads/${{ env.BRANCH }}

    - name: Compile Schemas
      id: compile
      shell: /bin/zsh --no-rcs --err-exit --pipe-fail {0}
      run: >-
        mkdir $BRANCH &&
        for file (*/${{ inputs.schema || '*' }}.ys)
          ys --json $file ${=ACTIONS_STEP_DEBUG:+-d --xtrace} |
          jq --indent ${TABSIZE:-2} --exit-status > $BRANCH/$file:t:r.json
      env:
        URL: https://${{ env.CDN }}${{ env.ref }}

    - name: Deploy
      if: inputs.schema == '' && steps.compile.conclusion == 'success'
      uses: s0/git-publish-subdir-action@ac113f6bfe8896e85a373534242c949a7ea74c98
      env:
        REPO: self
        FOLDER: ${{ env.BRANCH }}
        MESSAGE: "{msg}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_EMPTY_COMMITS: true
